FROM node:25.6.0-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends curl ffmpeg procps \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

USER node

STOPSIGNAL SIGTERM

CMD ["npm", "run", "start:dev"]
